[package]
name = "template"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
thiserror = "1.0.63"

[[bin]]
name = "template"
path = "src/main.rs" # replace bin.rs with name of your file
